-- STRATO — datos de arranque (categorías + productos placeholder)
-- Corré esto DESPUÉS de schema.sql. Podés borrar estas filas de ejemplo
-- cuando cargues tus productos reales desde el panel /admin.html.

-- ============ CATEGORIAS ============
insert into categorias (slug, nombre, descripcion_corta, orden) values ('iluminacion', 'Iluminación', 'Lámparas y veladores', 0) on conflict (slug) do nothing;
insert into categorias (slug, nombre, descripcion_corta, orden) values ('decoracion', 'Decoración', 'Floreros y objetos', 1) on conflict (slug) do nothing;
insert into categorias (slug, nombre, descripcion_corta, orden) values ('organizacion', 'Organización', 'Bandejas y contenedores', 2) on conflict (slug) do nothing;
insert into categorias (slug, nombre, descripcion_corta, orden) values ('jardin', 'Macetas y jardín', 'Macetas e interior verde', 3) on conflict (slug) do nothing;
insert into categorias (slug, nombre, descripcion_corta, orden) values ('personalizados', 'Personalizados', 'A pedido, con tu diseño', 4) on conflict (slug) do nothing;

-- ============ PRODUCTOS ============
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Lámpara Onda', (select id from categorias where slug = 'iluminacion'), 1890, ARRAY['Crudo','Terracota','Grafito']::text[], 'PLA multicolor', 'Lámpara de mesa con capas onduladas que dejan pasar una luz cálida y difusa. Impresa en una sola pieza, sin costuras.', 'Destacado', 0);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Velador Strato', (select id from categorias where slug = 'iluminacion'), 1450, ARRAY['Crudo','Piedra']::text[], 'PLA', 'Velador compacto de líneas rectas, pensado para mesa de luz. Zócalo E27, cable textil incluido.', null, 1);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Aplique Capas', (select id from categorias where slug = 'iluminacion'), 2200, ARRAY['Terracota','Grafito']::text[], 'PLA multicolor', 'Aplique de pared con relieve de capas visibles a propósito: la textura de la impresión como diseño.', 'Nuevo', 2);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Florero Degradé', (select id from categorias where slug = 'decoracion'), 990, ARRAY['Terracota/Crudo','Salvia/Crudo']::text[], 'PLA reciclado', 'Cada pieza sale con un degradé único: al imprimirse en dos tonos, no hay dos floreros iguales. Apto flores naturales con vaso interior.', 'Destacado', 3);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Centro de Mesa Terrazas', (select id from categorias where slug = 'decoracion'), 1350, ARRAY['Crudo','Piedra']::text[], 'PLA', 'Bandeja escultórica de niveles, pensada para centro de mesa o vitrina.', null, 4);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Portarretrato Líneas', (select id from categorias where slug = 'decoracion'), 590, ARRAY['Crudo','Grafito','Terracota']::text[], 'PLA', 'Portarretrato 10x15 con marco acanalado. Se apoya sola, sin vidrio.', null, 5);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Florero Organza', (select id from categorias where slug = 'decoracion'), 1190, ARRAY['Traslúcido','Crudo']::text[], 'PLA silk', 'Pared fina con acabado satinado que juega con la luz, inspirado en textiles livianos.', null, 6);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Bandeja Modular', (select id from categorias where slug = 'organizacion'), 780, ARRAY['Crudo','Piedra','Grafito']::text[], 'PLA', 'Bandeja de escritorio con divisiones para útiles, cargador y llaves. Apilable.', null, 7);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Organizador de Escritorio', (select id from categorias where slug = 'organizacion'), 1050, ARRAY['Grafito','Crudo']::text[], 'PLA', 'Tres compartimentos + porta lápices integrado. Base antideslizante.', 'Nuevo', 8);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Frutero Capas', (select id from categorias where slug = 'organizacion'), 1290, ARRAY['Terracota','Crudo']::text[], 'PLA multicolor', 'Frutero de dos niveles con estructura calada, liviano y fácil de lavar.', null, 9);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Maceta Terraza', (select id from categorias where slug = 'jardin'), 690, ARRAY['Terracota','Salvia','Crudo']::text[], 'PLA reciclado', 'Maceta con plato integrado y reserva de agua. Disponible en tres tamaños.', 'Destacado', 10);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Macetero Colgante', (select id from categorias where slug = 'jardin'), 590, ARRAY['Crudo','Piedra']::text[], 'PLA', 'Para plantas colgantes tipo potus. Incluye soporte de cuerda de algodón.', null, 11);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Set Suculentas x3', (select id from categorias where slug = 'jardin'), 990, ARRAY['Mix Tierra']::text[], 'PLA multicolor', 'Tres macetas mini en tonos tierra, ideales para escritorio o ventana.', null, 12);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Pieza a Medida', (select id from categorias where slug = 'personalizados'), null, ARRAY['A elección']::text[], 'PLA / PETG', 'Diseñamos e imprimimos tu idea: logo, repuesto, regalo o pieza funcional. Contanos qué necesitás y te devolvemos un presupuesto.', null, 13);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Topper Personalizado', (select id from categorias where slug = 'personalizados'), null, ARRAY['A elección']::text[], 'PLA', 'Topper de torta o evento con nombre, fecha o diseño a pedido.', null, 14);
insert into productos (nombre, categoria_id, precio, colores, material, descripcion, tag, orden) values ('Placa Nombre para Puerta', (select id from categorias where slug = 'personalizados'), null, ARRAY['A elección']::text[], 'PLA', 'Cartel personalizado para puerta, escritorio o vidriera con tipografía a elección.', null, 15);
